language: node_js

node_js:
  - "16"

install:
  - npm install

script:
  - npm run build
  
after_success:
  - git config --global credential.helper store
  - git config --global user.name Travis-ci
  - git config --global user.email ci@travis-ci.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
  - git --work-tree dist add .travis.yml

  # Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/

  # blocklist
branches:
  except:
  - gh-pages